### ISSUE TITLE
Why does notetaker_notes table also holds modid

### ISSUE THREAD

**Issue by mudrd8mz** [jlb224/notetaker#4]
The notetaker_notes has a foreign key notetakerid that creates the 1:N relation between notetaker instance and notetaker_notes. But then the notetaker_notes also has another field that links to the same notetaker instance.

This violates the https://en.wikipedia.org/wiki/Third_normal_form and should be avoided - unless I am missing something?

**Comment by jlb224** [comment]
Resolved. Code refactored to remove unnecessary modid column
